### ISSUE TITLE
v1.24.0 ReferenceError: window is not defined

### ISSUE THREAD

**Issue by dragma** [ubilabs/react-geosuggest#172]
Hi, 
Since the last release (v1.24.0), the module can no longer be used server side.
Here is the error I get :

```
ReferenceError: window is not defined
    at Geosuggest.componentWillMount (/path/to/my/project/node_modules/react-geosuggest/module/Geosuggest.js:190:49)
    at [object Object].ReactCompositeComponentMixin.performInitialMount (/path/to/my/project/node_modules/react/lib/ReactCompositeComponent.js:336:12)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/path/to/my/project/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.ReactReconciler.mountComponent (/path/to/my/project/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/path/to/my/project/node_modules/react/lib/ReactMultiChild.js:215:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/path/to/my/project/node_modules/react/lib/ReactDOMComponent.js:611:32)
    at ReactDOMComponent.Mixin.mountComponent (/path/to/my/project/node_modules/react/lib/ReactDOMComponent.js:493:29)
    at Object.ReactReconciler.mountComponent (/path/to/my/project/node_modules/react/lib/ReactReconciler.js:46:35)
    at [object Object].ReactCompositeComponentMixin.performInitialMount (/path/to/my/project/node_modules/react/lib/ReactCompositeComponent.js:357:34)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/path/to/my/project/node_modules/react/lib/ReactCompositeComponent.js:244:21)
    at Object.ReactReconciler.mountComponent (/path/to/my/project/node_modules/react/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/path/to/my/project/node_modules/react/lib/ReactMultiChild.js:215:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/path/to/my/project/node_modules/react/lib/ReactDOMComponent.js:611:32)
    at ReactDOMComponent.Mixin.mountComponent (/path/to/my/project/node_modules/react/lib/ReactDOMComponent.js:493:29)
    at Object.ReactReconciler.mountComponent (/path/to/my/project/node_modules/react/lib/ReactReconciler.js:46:35)
    at [object Object].ReactCompositeComponentMixin.performInitialMount (/path/to/my/project/node_modules/react/lib/ReactCompositeComponent.js:357:34)
```

Btw, thanks for this module :)

Regards,

Flo

**Comment by Caerostris** [comment]
I have created PR #173 which should fix this issue.
